### ISSUE TITLE
Installation issue on WordPress 

### ISSUE THREAD

**Issue by larnoult** [compucorp/uk.co.compucorp.civicrm.prospect#98]
Hello, 
I'm running civiCRM 5.50.0 on WordPress 6.0
I'm using [this fork of civiCase](https://github.com/coopsymbiotic/uk.co.compucorp.civicase) together with this [Shoreditch workaround for WordPress](https://lab.civicrm.org/extensions/shoreditchwpworkarounds) extension. 
I would have liked to try your extension.. but installation fails with such error: 
```
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => install
    [params] => Array
        (
            [keys] => Array
                (
                    [0] => uk.co.compucorp.civicrm.prospect
                )

            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/CRM/Prospect/Setup/MoveCustomFieldsToWorkFlowCaseType.php(30): civicrm_api3()
#1 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/CRM/Prospect/Upgrader.php(66): CRM_Prospect_Setup_MoveCustomFieldsToWorkFlowCaseType->apply()
#2 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/CRM/Prospect/Upgrader/Base.php(326): CRM_Prospect_Upgrader->install()
#3 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/prospect.civix.php(131): CRM_Prospect_Upgrader_Base->onInstall()
#4 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/prospect.php(54): _prospect_civix_civicrm_install()
#5 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(61): prospect_civicrm_install()
#6 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(33): CRM_Extension_Manager_Module->callHook()
#7 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager.php(293): CRM_Extension_Manager_Module->onPreInstall()
#8 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#9 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#10 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke()
#11 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest()
#12 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/api/api.php(22): Civi\API\Kernel->runSafe()
#13 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(63): civicrm_api()
#14 phar:///usr/local/bin/cv/src/Command/ExtensionEnableCommand.php(91): Civi\Cv\Command\BaseCommand->callApiSuccess()
#15 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\ExtensionEnableCommand->execute()
#16 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#17 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 phar:///usr/local/bin/cv/src/Application.php(59): Symfony\Component\Console\Application->doRun()
#19 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun()
#20 phar:///usr/local/bin/cv/src/Application.php(26): Symfony\Component\Console\Application->run()
#21 phar:///usr/local/bin/cv/bin/cv(27): Civi\Cv\Application::main()
#22 /usr/local/bin/cv(14): require('phar:///usr/loc...')
#23 {main}
            [is_error] => 1
            [error_message] => Supplied Sub type is not valid for the specified entitiy
        )

)
```
Any idea how to fix it?
Thx in advance,

**Comment by larnoult** [comment]
I ran `cv flush` and retried the installation (`cv en prospect`), and now I'm getting this new error: 
```
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => install
    [params] => Array
        (
            [keys] => Array
                (
                    [0] => uk.co.compucorp.civicrm.prospect
                )

            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [error_code] => already exists
            [trace] => #0 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(922): CRM_Core_Error::exceptionHandler()
#1 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB.php(997): PEAR_Error->__construct()
#2 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(575): DB_Error->__construct()
#3 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR::_raiseError()
#4 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/common.php(1928): PEAR->__call()
#5 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/mysqli.php(936): DB_common->raiseError()
#6 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/mysqli.php(406): DB_mysqli->mysqliRaiseError()
#7 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/common.php(1234): DB_mysqli->simpleQuery()
#8 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(2696): DB_common->query()
#9 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(1245): DB_DataObject->_query()
#10 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(660): DB_DataObject->insert()
#11 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomField.php(2141): CRM_Core_DAO->save()
#12 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomField.php(189): CRM_Core_BAO_CustomField::createCustomFieldRecord()
#13 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(172): CRM_Core_BAO_CustomField::writeRecords()
#14 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Action/CustomField/CustomFieldSaveTrait.php(29): Civi\Api4\Generic\DAOSaveAction->write()
#15 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(139): Civi\Api4\Action\CustomField\Save->write()
#16 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/DAOSaveAction.php(35): Civi\Api4\Generic\DAOSaveAction->writeObjects()
#17 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Provider/ActionObjectProvider.php(69): Civi\Api4\Generic\DAOSaveAction->_run()
#18 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(149): Civi\Api4\Provider\ActionObjectProvider->invoke()
#19 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/Api4/Generic/AbstractAction.php(234): Civi\API\Kernel->runRequest()
#20 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Utils/Migrate/Import.php(355): Civi\Api4\Generic\AbstractAction->execute()
#21 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Utils/Migrate/Import.php(66): CRM_Utils_Migrate_Import->customFields()
#22 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Utils/Migrate/Import.php(43): CRM_Utils_Migrate_Import->runXmlElement()
#23 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/CRM/Prospect/Upgrader/Base.php(112): CRM_Utils_Migrate_Import->run()
#24 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/CRM/Prospect/Upgrader/Base.php(322): CRM_Prospect_Upgrader_Base->executeCustomDataFileByAbsPath()
#25 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/prospect.civix.php(131): CRM_Prospect_Upgrader_Base->onInstall()
#26 /www/parlemonde_330/public/wp-content/uploads/civicrm/ext/uk.co.compucorp.civicrm.prospect-2.0.0-beta.9/prospect.php(54): _prospect_civix_civicrm_install()
#27 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(61): prospect_civicrm_install()
#28 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(33): CRM_Extension_Manager_Module->callHook()
#29 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager.php(293): CRM_Extension_Manager_Module->onPreInstall()
#30 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#31 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#32 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke()
#33 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest()
#34 /www/parlemonde_330/public/wp-content/plugins/civicrm/civicrm/api/api.php(22): Civi\API\Kernel->runSafe()
#35 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(63): civicrm_api()
#36 phar:///usr/local/bin/cv/src/Command/ExtensionEnableCommand.php(91): Civi\Cv\Command\BaseCommand->callApiSuccess()
#37 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\ExtensionEnableCommand->execute()
#38 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#39 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#40 phar:///usr/local/bin/cv/src/Application.php(59): Symfony\Component\Console\Application->doRun()
#41 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun()
#42 phar:///usr/local/bin/cv/src/Application.php(26): Symfony\Component\Console\Application->run()
#43 phar:///usr/local/bin/cv/bin/cv(27): Civi\Cv\Application::main()
#44 /usr/local/bin/cv(14): require('phar:///usr/loc...')
#45 {main}
            [is_error] => 1
            [error_message] => DB Error: already exists
        )

)
```

**Comment by chumkui** [comment]
Taking a look at this again and I just installed on Drupal and got the same sub-type message... I think it is the same issue already reported #97. I'll take a look and see if I can see anything.  I am not sure this is supported - nothing seems to have happened code wise in quite a long time, my question about changing status on a prospect back in 2021 was never answered so I never properly evaluated. I'll drop Jamie an email to see what's up with this and whether it is still a valid project.  The reason you are getting the DB Error: already exists is due to the database changes that are made on installation before the failure - it does not check if data tables already exists when you try to reinstall.

**Comment by masetto** [comment]
Hi @chumkui, have you heard if it is still supported? I have the same problem and I don't know how to cancel database changes made by extension. Thank you.

**Comment by masetto** [comment]
I investigated: the problem is in `CRM/Prospect/Setup/MoveCustomFieldsToWorkFlowCaseType.php` at row 31:

```
      civicrm_api3('CustomGroup', 'create', [
        'id' => $value['id'],
        'extends_entity_column_value' => CRM_Core_DAO::VALUE_SEPARATOR . $workflowCaseType['id'] . CRM_Core_DAO::VALUE_SEPARATOR,
      ]);
```
`extends` parameter is not set and by default `civicrm/CRM/Core/BAO/CustomGroup.php` add `Contact`.
We should ask @tunbola what is the logic of this file...I didn't understand it.
